"""Init

Revision ID: 8a5f37575391
Revises:
Create Date: 2022-12-06 18:14:06.130335

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8a5f37575391"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("staff", "admin", "super_admin", name="userrolesenum"), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("pk"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "jwt_sessions",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("user_pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_denied", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_pk"],
            ["users.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("pk"),
        sa.UniqueConstraint("refresh_token"),
    )
    op.create_index(op.f("ix_jwt_sessions_user_pk"), "jwt_sessions", ["user_pk"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jwt_sessions_user_pk"), table_name="jwt_sessions")
    op.drop_table("jwt_sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
